#!/bin/csh -f
#
#tar up files, pipe through btoa to mail.
#recieve by saving mail in temp file, then "untarmail temp"
if ($#argv < 3) then
  echo "usage:  tarmail  mailpath  subject-string  directory-or-file-name(s)"
  exit
else
  set mailpath = $1
  echo mailpath = $mailpath
  shift
  set subject = $1
  echo subject-string = $subject
  shift
  echo files = $*
  tar cvf - $* | btoa | mail -s $subject $mailpath
endif
exit
#
# 	$Source: /afs/dev.mit.edu/source/repository/athena/bin/tarmail/tarmail,v $
#	$Author: epeisach $
#	$Locker:  $
#	$Header: /afs/dev.mit.edu/source/repository/athena/bin/tarmail/tarmail,v 1.2 1990-03-26 13:45:47 epeisach Exp $
#
