#!/bin/csh
#
#atob and untar mail sent via tarmail
atob < ${1} | tar xvpf -
set destfile = `echo ${1} | sed 's"/"."g'`
mv ${1} /tmp/${destfile}.$$
echo tarmail file moved to: /tmp/${destfile}.$$
exit
#
# 	$Source: /afs/dev.mit.edu/source/repository/athena/bin/tarmail/untarmail,v $
#	$Author: jtkohl $
#	$Locker:  $
#	$Header: /afs/dev.mit.edu/source/repository/athena/bin/tarmail/untarmail,v 1.3 1985-04-30 18:18:22 jtkohl Exp $
#
