#!/bin/csh -f
#
#atob and untar mail sent via tarmail
atob < ${1} | tar xvpf -
set destfile = `echo ${1} | sed 's"/"."g'`
mv ${1} /tmp/${destfile}.$$
echo tarmail file moved to: /tmp/${destfile}.$$
exit
#
# 	$Source: /afs/dev.mit.edu/source/repository/athena/bin/tarmail/untarmail,v $
#	$Author: epeisach $
#	$Locker:  $
#	$Header: /afs/dev.mit.edu/source/repository/athena/bin/tarmail/untarmail,v 1.4 1990-03-26 13:46:09 epeisach Exp $
#
